name: check

on:
  pull_request:
  push:
    branches:
      - master
      - dev/*

jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: run tests
        run: go test ./...
